[workspace]

members = [
    "resctl/below",
    "resctl/below/below_derive",
    "resctl/below/if",
    "resctl/common/cgroupfs",
    "resctl/common/cgroupfs/if",
    "resctl/common/procfs",
    "resctl/common/procfs/if",
]
