[package]
name = "dump"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "Apache-2.0"
include = ["src/**/*.rs"]

[dependencies]
below_derive = { path = "../below_derive" }
common = { path = "../common" }
model = { path = "../model" }
procfs = { path = "../../common/procfs" }
store = { path = "../store" }
anyhow = "1.0"
cursive = { version = "0.15.0", default-features = false, features = ["crossterm", "termion"] }
regex = "1.3.7"
serde_json = { version = "1.0", features = ["float_roundtrip"] }
slog = { version = "2.5", features = ["max_level_debug"] }
structopt = "0.3.7"
toml = "=0.5.7"
