[package]
name = "model"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "Apache 2.0"
include = ["src/**/*.rs"]

[dependencies]
below-thrift = { path = "../if" }
below_derive = { path = "../below_derive" }
cgroupfs = { path = "../../common/cgroupfs" }
common = { path = "../common" }
procfs = { path = "../../common/procfs" }
anyhow = "1.0"
cursive = { git = "https://github.com/gyscos/cursive", rev = "750a7af6c79946ba7c87253714a6957abdd8bfd3" }
hostname = "0.3"
slog = { version = "2.5", features = ["max_level_debug"] }
