[package]
name = "view"
edition = "2018"
version = "0.1.0"
authors = ['Facebook']
license = "Apache 2.0"
include = ["src/**/*.rs"]

[dependencies]
below_derive = { path = "../below_derive" }
common = { path = "../common" }
procfs = { path = "../../common/procfs" }
store = { path = "../store" }
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
cursive = { git = "https://github.com/gyscos/cursive", rev = "750a7af6c79946ba7c87253714a6957abdd8bfd3" }
humantime = "1.3"
libc = "0.2"
slog = { version = "2.5", features = ["max_level_debug"] }
